### PR TITLE
fix(useAtomsSnapshot): export useMutableSource as secret from core

### LINKED ISSUE #492: [BUG] TypeError: source[GET_VERSION] is not a function
jotai version: 0.16.6

I get this error when I try to get atoms snapshot. 

I implemented the official [example](https://docs.pmnd.rs/jotai/api/devtools#use-atoms-snapshot), and checked that **process.env.NODE_ENV** equals to development. However, the error still persists.

### PR DESCRIPTION
**Pull request by Thisen**
Fixes #492

### CODE REVIEW

File: src/devtools/useAtomsSnapshot.ts [hunk 1]
```diff
@@ -1,12 +1,10 @@
...
-import type { Scope } from '../core/atom'
+import {
+  SECRET_INTERNAL_getStoreContext as getStoreContext,
+  SECRET_INTERNAL_useMutableSource as useMutableSource,
+} from 'jotai'
 import type { AtomState, State } from '../core/vanilla'
-
-// XXX across bundles, this is actually copying code
-import { useMutableSource } from '../core/useMutableSource'
+import { Atom, Scope } from '../core/atom'
```
Comment (dai-shi) [inline src/devtools/useAtomsSnapshot.ts:7]:
```suggestion
import type { Atom, Scope } from '../core/atom'
```
We are strict about this. This helps a bit to understand what code is across bundles.

Comment (Thisen) [reply src/devtools/useAtomsSnapshot.ts:7]: That's a mistake, will fix it right away

**Review by dai-shi — APPROVED** [review]
Thanks.
