### PR TITLE
fix(core): handle an edge case of changing dependencies without changing atom value

### LINKED ISSUE #947: [Regression Bug] Updated atom value not propagated to component
I am using an atom (A) to control if an atom (B) should return the value of an atom (C) otherwise a default value is returned.  See the example below: https://codesandbox.io/s/dark-http-bsili?file=/src/App.tsx

```ts
const aAtom = atom<any>(false);
aAtom.debugLabel = "aAtom";
aAtom.onMount = (set) => {
    console.log("onMount: aAtom");
    setTimeout(() => {
        set(true);
    }, 1000);
};

const cAtom = atom<any>(1);
cAtom.debugLabel = "cAtom";
cAtom.onMount = (set) => {
    console.log("onMount: cAtom");
    set(2);
};

const bAtom = atom<any>((get) => {
    const a = get(aAtom);
    console.log("a=", a);
    if (a) {
        return get(cAtom);
    }
    return 1;
});
bAtom.debugLabel = "bAtom";

```

The problem is, that the changed value of atom (C) is never propagated to the invoking component through `useAtom`. The error occurs when there is no externally triggered rendering within the calling component, which re-evaluates the `useAtom` hook. I think, there is somewhere a `flushPending` missing. I tried to figure out what could be a possible fix, but I did not found any good solution. 

Affects version `1.5.0`.  Worked with ~~`1.4.2`~~ `1.4.9`.

----

BTW:  I think the `useEffect` call at https://github.com/pmndrs/jotai/blob/main/src/core/useAtom.ts#L103-L105 should pass its dependencies. If so, a forced rendering has no effect anymore on the bug above.

```ts
  useEffect(() => {
    store[COMMIT_ATOM](atom, version)
  }, [store, atom, version]);
```

### PR DESCRIPTION
**Pull request by xbaun**
fix #947 

(edit by @dai-shi) this is done by a hacky way. wish to have a nicer way.

### CODE REVIEW

File: src/core/store.ts [hunk 1]
```diff
@@ -423,13 +422,12 @@ export const createStore = (
...
-              if (
-                isSuspensePromise(e) &&
-                isSuspensePromiseAlreadyCancelled(e)
-              ) {
+              if (isSuspensePromise(e)) {
                 // schedule another read later
                 // FIXME not 100% confident with this code
-                e.then(() => readAtomState(version, atom, true))
+                e.then(() => {
+                  readAtomState(version, atom, true)
```
Comment (Aslemammad) [inline src/core/store.ts:429]: What's the difference here? Like readAtomState won't pass the returned value to the next `then`?

Comment (dai-shi) [reply src/core/store.ts:429]: Sorry for confusion. This doesn't mean anything special. Just making it clear that it returns void.

**Comment by dai-shi** [comment]
Okay, seems like I was solving a different/general problem. Let's separate that fix in a separate PR and come back to this.
